### ISSUE TITLE
Spread operator syntax error

### ISSUE THREAD

**Issue by cezarsmpio** [weblogixx/generator-react-webpack-alt#3]
When I try use spread operator, simple code:

``` javascript
import alt from 'components/Dispatcher';

class NotificationActions {

  send(notification) {
    return notification;
  }

  success(n) {
    this.send({
      level: 'success',
      ...n
    });
  }

  error(n) {
    this.send({
      level: 'error',
      ...n
    });
  }

  warning(n) {
    this.send({
      level: 'warning',
      ...n
    });
  }

  info(n) {
    this.send({
      level: 'info',
      ...n
    });
  }

}

export default alt.createActions(NotificationActions);
```

Error:

``` javascript
./src/actions/NotificationActions.js
Module build failed: SyntaxError: /Users/cezarluiz/Documents/Web/gobiker-cms/src/actions/NotificationActions.js: Unexpected token (10:9)
   8 | 
   9 |   success(n) {
> 10 |     let {...obj} = n;
     |          ^
  11 | 
  12 |     console.log(obj);
  13 |   }
    at Parser.pp.raise (/Users/cezarluiz/Documents/Web/gobiker-cms/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/Users/cezarluiz/Documents/Web/gobiker-cms/node_modules/babylon/lib/parser/util.js:91:8)
    at Parser.pp.parseIdentifier (/Users/cezarluiz/Documents/Web/gobiker-cms/node_modules/babylon/lib/parser/expression.js:1009:10)
    at Parser.pp.parsePropertyName (/Users/cezarluiz/Documents/Web/gobiker-cms/node_modules/babylon/lib/parser/expression.js:831:135)
    at Parser.pp.parseObj (/Users/cezarluiz/Documents/Web/gobiker-cms/node_modules/babylon/lib/parser/expression.js:747:12)
    at Parser.pp.parseBindingAtom (/Users/cezarluiz/Documents/Web/gobiker-cms/node_modules/babylon/lib/parser/lval.js:161:19)
    at Parser.pp.parseVarHead (/Users/cezarluiz/Documents/Web/gobiker-cms/node_modules/babylon/lib/parser/statement.js:581:18)
    at Parser.<anonymous> (/Users/cezarluiz/Documents/Web/gobiker-cms/node_modules/babylon/lib/plugins/flow.js:957:13)
    at Parser.parseVarHead (/Users/cezarluiz/Documents/Web/gobiker-cms/node_modules/babylon/lib/plugins/flow.js:957:13)
    at Parser.pp.parseVar (/Users/cezarluiz/Documents/Web/gobiker-cms/node_modules/babylon/lib/parser/statement.js:564:10)
 @ ./src/components/Main.js 23:27-65onSocketMsg.errors @ client:44sock.onmessage @ client:79EventTarget.dispatchEvent @ eventtarget.js:49(anonymous function) @ main.js:274SockJS._transportMessage @ main.js:272EventEmitter.emit @ emitter.js:44WebSocketTransport.ws.onmessage @ websocket.js:35
```

**Comment by weblogixx** [comment]
Hi @CezarLuiz0,

please have a look to https://github.com/newtriks/generator-react-webpack/issues/177. Spread operator is currently not implemented as a stable for ES2015, so there is no support for it. You can add it yourself with just a little change, see the linked issue of generator-react-webpack.

**Comment by cezarsmpio** [comment]
Hi @weblogixx, thanks! I will try use this solution.

**Comment by cezarsmpio** [comment]
This did not solve the problem ... The presets babel is already installed. Any idea?

**Comment by weblogixx** [comment]
Its about preset-babel-stage-2, not the regular one. Please have a look at the linked post, you have to add the preset and install it via nom
